Exercise 1: Creating and Manipulating Arrays

Creating 1D array with elements 10 to 50 inclusive

In [4]:
import numpy as np
arr=np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Extracting elements from 5 to 15

In [5]:
print(arr[5:15])

[15 16 17 18 19 20 21 22 23 24]


Reverse the array

In [8]:
print(arr[: :-1])

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Print every 3rd element

In [9]:
print(arr[::3])

[10 13 16 19 22 25 28 31 34 37 40 43 46 49]


Exercise 2: 2D Array Indexing


Create a 3×3 matrix with values 1 to 9.

In [11]:
import numpy as np
arr=np.array([[0,1,2],
             [4,5,6],
             [7,8,9]])
print(arr)

[[0 1 2]
 [4 5 6]
 [7 8 9]]


Extract the second row.

In [12]:
print(arr[1])

[4 5 6]


Extract the first column.

In [15]:
print(arr[:,1])

[1 5 8]


In [16]:
print(arr[:,0])

[0 4 7]


Extract a 2×2 submatrix from the top-left corner.

In [24]:
print(arr[:2,:2])

[[0 1]
 [4 5]]


Exercise 3: Arithmetic Operations

Create two arrays: [1, 2, 3] and [4, 5, 6].

In [26]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
#add
print(a+b)
#subtract
print(a-b)

[5 7 9]
[-3 -3 -3]
